module.exports = {
    gender: ['Male', 'Female', 'notToMention'],
    roles: ['user', 'admin'],
    tokenType: 'Bearer',
    errorMessage: {
        SUCCESS: 'SUCCESS',
        FAILED: 'FAILED',
        ACCESS_DENIED: 'ACCESS_DENIED',
        TOKEN_EXPIRED: 'TOKEN_EXPIRED',
        TOKEN_UNAUTHORIZED: 'TOKEN_UNAUTHORIZED',
        REQUIRED: 'REQUIRED',
        BLOCKED: 'BLOCKED_ACCOUNT',
        INVALID_PASSWORD: 'INVALID_PASSWORD',
        USER_SUCCESSFULLY_REGISTERED: 'USER_SUCCESSFULLY_REGISTERED',
        LOGGED_IN_SUCCESSFULLY: 'USER_SUCCESSFULLY_LOGGEDIN',
        INVALID_USER_NAME: 'INVALID_USER_NAME',
        VALIDATION_ERROR: 'VALIDATION_ERROR',
        NOT_FOUND: 'NOT_FOUND',
        NO_USER: 'NO-USER_FOUND',
        NO_SUBMISSION_FOUND: "NO_SUBMISSION_FOUND"
    },
};
